/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.LivroDao;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import models.Livro;

/**
 *
 * @author Alexandre
 */
public class TelaCadastro extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastro
     */
    Livro livro;
    JFileChooser fileChooser;
    public TelaCadastro() {
        initComponents();
        livro = new Livro();
        fileChooser = new JFileChooser();
        Date data = new Date();
        livro.setDataDeCadastro(new Timestamp(data.getTime()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new javax.swing.JLabel();
        txtNomeDoLivro = new javax.swing.JTextField();
        txtImagemLivro = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        anoedicao = new javax.swing.JLabel();
        txtAnoEdicao = new javax.swing.JTextField();
        notausuario = new javax.swing.JLabel();
        txtNotaUsuario = new javax.swing.JTextField();
        resenha = new javax.swing.JLabel();
        txtResenha = new javax.swing.JTextField();
        cadastro = new javax.swing.JLabel();
        btnProcuraImagem = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        buscar = new javax.swing.JLabel();
        txtBuscarLivro = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtDataDeCadastro = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(594, 528));

        Nome.setText("Nome:");

        txtNomeDoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeDoLivroActionPerformed(evt);
            }
        });

        txtImagemLivro.setBackground(new java.awt.Color(153, 153, 153));
        txtImagemLivro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtImagemLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_book_cadastro.png"))); // NOI18N
        txtImagemLivro.setText("Imagem do Livro");
        txtImagemLivro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtImagemLivro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtImagemLivro.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Tela de Cadastro");

        Autor.setText("Autor:");

        anoedicao.setText("Ano de edição:");

        notausuario.setText("Nota do usuário:");

        resenha.setText("Resenha:");

        cadastro.setText("Data de Cadastramento:");

        btnProcuraImagem.setText("Procurar Imagem");
        btnProcuraImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcuraImagemActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_add_book.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(100, 33));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_alterar_book.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setPreferredSize(new java.awt.Dimension(100, 33));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_remove_book.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(100, 33));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        buscar.setText("Buscar Livro:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(notausuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtResenha, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNotaUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                                .addComponent(txtNomeDoLivro, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(anoedicao)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtAnoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(1, 1, 1))
                                    .addComponent(resenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cadastro)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtDataDeCadastro)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnProcuraImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(txtImagemLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Titulo)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscar)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscarLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeDoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Autor)
                        .addGap(10, 10, 10)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anoedicao)
                            .addComponent(txtAnoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadastro)
                            .addComponent(txtDataDeCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(notausuario)
                        .addGap(10, 10, 10)
                        .addComponent(txtNotaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(resenha))
                    .addComponent(txtImagemLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtResenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnProcuraImagem)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeDoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeDoLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeDoLivroActionPerformed

    private void btnProcuraImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcuraImagemActionPerformed
        // TODO add your handling code here:

        fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Procurar imagem");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Filtro para imagem.
        FileNameExtensionFilter filter = new FileNameExtensionFilter("imagem", "jpg","jpeg","png");
        fileChooser.setFileFilter(filter);
        int retorno = fileChooser.showOpenDialog(this);
        if(retorno == JFileChooser.APPROVE_OPTION){
            try {
                BufferedImage upload = ImageIO.read(fileChooser.getSelectedFile());
                Image foto = upload.getScaledInstance(185, 232, Image.SCALE_SMOOTH);
                txtImagemLivro.setIcon(new ImageIcon(foto));
                livro.processarImagem(fileChooser.getSelectedFile().getPath());
                System.out.println(txtImagemLivro.getText());
            } catch (IOException ex) {
                Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnProcuraImagemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        //Criar objeto livro e passa para classe LivroDao.
        salvarLivro();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        LivroDao dao = new LivroDao();
        System.out.print("Nome:" + txtBuscarLivro.getText());
        try {
            livro = dao.buscarLivroNome(txtBuscarLivro.getText());
            if(livro != null){
                txtNomeDoLivro.setText(livro.getNomeDoLivro());
                txtAutor.setText(livro.getAutor());
                txtAnoEdicao.setText(String.valueOf(livro.getAnoDeEdicao()));
                txtDataDeCadastro.setText(String.valueOf(livro.getDataDeCadastro()));
                txtNotaUsuario.setText(livro.getNotaDoUsuario());
                txtResenha.setText(livro.getResenha());
                BufferedImage upload = ImageIO.read(livro.getImagemLivro());
                Image foto = upload.getScaledInstance(185, 232, Image.SCALE_SMOOTH);
                txtImagemLivro.setIcon(new ImageIcon(foto));
                txtImagemLivro.setText("");
                
            }else{
                JOptionPane.showMessageDialog(this, "Livro não encontrado.");
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarLivro();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        deletarLivro();
    }//GEN-LAST:event_btnExcluirActionPerformed
    public void obterDados(){
        livro.setNomeDoLivro(txtNomeDoLivro.getText());
        livro.setAutor(txtAutor.getText());
        livro.setAnoDeEdicao(Integer.valueOf(txtAnoEdicao.getText()));
        Date data = new Date();
        livro.setDataDeCadastro(new Timestamp(data.getTime()));
        livro.setNotaDoUsuario(txtNotaUsuario.getText());
        livro.setResenha(txtResenha.getText());
        File imagemFile = fileChooser.getSelectedFile();
        if(imagemFile != null){
            livro.setImagemLivro(imagemFile);
        }
        
        
    }
    
    //Metodo para salvar dados no banco.
    public void salvarLivro(){
        
        obterDados();
        //Inserir no banco.
        LivroDao dao = new LivroDao();
        try {
            if(dao.inserirLivro(livro)){
                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso.");
            }else{
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void deletarLivro(){
        
        LivroDao dao = new LivroDao();    
        try{
            boolean ok = dao.excluir(txtNomeDoLivro.getText());
            if(ok){
                JOptionPane.showMessageDialog(this, "Deletado com sucesso");
            }else{
                JOptionPane.showMessageDialog(this, "Não pode ser deletado");
            }
        }catch(SQLException e){
            
        }
    }
    
    public void alterarLivro(){
        obterDados();
        LivroDao dao = new LivroDao();
        try{
            if(dao.alterar(livro)){
            JOptionPane.showMessageDialog(this, "Alterado com sucesso.");
        }else{
            JOptionPane.showMessageDialog(this, "Alteração não efetuada.");
        }
        }catch(SQLException ex){
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Autor;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel anoedicao;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnProcuraImagem;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel notausuario;
    private javax.swing.JLabel resenha;
    private javax.swing.JTextField txtAnoEdicao;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBuscarLivro;
    private javax.swing.JTextField txtDataDeCadastro;
    private javax.swing.JLabel txtImagemLivro;
    private javax.swing.JTextField txtNomeDoLivro;
    private javax.swing.JTextField txtNotaUsuario;
    private javax.swing.JTextField txtResenha;
    // End of variables declaration//GEN-END:variables
}
