
import dao.LivroDao;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import models.Livro;
import telas.TelaCadastro;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alexandre
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela(){
        initComponents();
        File destino =  new File("imagensLivros");
        destino.mkdir();
        LivroDao dao = new LivroDao();
        List<Livro> lista = null;
        try {
            lista = dao.obterLivros();
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.print("Tamanho: "+ lista.size());
        if(lista != null){
            //System.out.println("Livro: "+ lista.get(0).getNomeDoLivro());
            DefaultListModel<String> model = new DefaultListModel<String>();
            for(int i = 0; i < lista.size(); i++){
                model.addElement(lista.get(i).getNomeDoLivro());
            }
            jListLivros.setModel(model);
        }else{
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanelMenu = new javax.swing.JPanel();
        NomeApp = new javax.swing.JLabel();
        btnInicio = new javax.swing.JPanel();
        txtInicio = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JPanel();
        txtCadastro = new javax.swing.JLabel();
        btnSobrePanel1 = new javax.swing.JPanel();
        txtSobre1 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jConteudoInicial = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListLivros = new javax.swing.JList<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanelMenu.setBackground(new java.awt.Color(42, 86, 159));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(130, 302));

        NomeApp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NomeApp.setForeground(new java.awt.Color(255, 255, 255));
        NomeApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_app.png"))); // NOI18N
        NomeApp.setText("LivrariaOS");
        NomeApp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NomeApp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnInicio.setBackground(new java.awt.Color(42, 86, 159));
        btnInicio.setPreferredSize(new java.awt.Dimension(140, 50));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInicioMousePressed(evt);
            }
        });

        txtInicio.setBackground(new java.awt.Color(42, 86, 159));
        txtInicio.setForeground(new java.awt.Color(255, 255, 255));
        txtInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_home_branco.png"))); // NOI18N
        txtInicio.setText("Início");
        txtInicio.setIconTextGap(10);

        javax.swing.GroupLayout btnInicioLayout = new javax.swing.GroupLayout(btnInicio);
        btnInicio.setLayout(btnInicioLayout);
        btnInicioLayout.setHorizontalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnInicioLayout.setVerticalGroup(
            btnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCadastro.setBackground(new java.awt.Color(42, 86, 159));
        btnCadastro.setPreferredSize(new java.awt.Dimension(140, 50));
        btnCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastroMousePressed(evt);
            }
        });

        txtCadastro.setBackground(new java.awt.Color(42, 86, 159));
        txtCadastro.setForeground(new java.awt.Color(255, 255, 255));
        txtCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_book_branco.png"))); // NOI18N
        txtCadastro.setText("Cadastro");
        txtCadastro.setIconTextGap(10);

        javax.swing.GroupLayout btnCadastroLayout = new javax.swing.GroupLayout(btnCadastro);
        btnCadastro.setLayout(btnCadastroLayout);
        btnCadastroLayout.setHorizontalGroup(
            btnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCadastroLayout.setVerticalGroup(
            btnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSobrePanel1.setBackground(new java.awt.Color(42, 86, 159));
        btnSobrePanel1.setPreferredSize(new java.awt.Dimension(140, 50));
        btnSobrePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSobrePanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSobrePanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSobrePanel1MousePressed(evt);
            }
        });

        txtSobre1.setBackground(new java.awt.Color(42, 86, 159));
        txtSobre1.setForeground(new java.awt.Color(255, 255, 255));
        txtSobre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Info_branco.png"))); // NOI18N
        txtSobre1.setText("Sobre");
        txtSobre1.setIconTextGap(10);

        javax.swing.GroupLayout btnSobrePanel1Layout = new javax.swing.GroupLayout(btnSobrePanel1);
        btnSobrePanel1.setLayout(btnSobrePanel1Layout);
        btnSobrePanel1Layout.setHorizontalGroup(
            btnSobrePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSobrePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSobre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSobrePanel1Layout.setVerticalGroup(
            btnSobrePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSobrePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSobre1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSobrePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addComponent(btnSobrePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jListLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLivrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListLivros);

        javax.swing.GroupLayout jConteudoInicialLayout = new javax.swing.GroupLayout(jConteudoInicial);
        jConteudoInicial.setLayout(jConteudoInicialLayout);
        jConteudoInicialLayout.setHorizontalGroup(
            jConteudoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConteudoInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addContainerGap())
        );
        jConteudoInicialLayout.setVerticalGroup(
            jConteudoInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConteudoInicialLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 398, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(jConteudoInicial, "card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseEntered
        // TODO add your handling code here:
        btnCadastro.setBackground(new java.awt.Color(31, 121, 189));
        txtCadastro.setForeground(java.awt.Color.WHITE);
        
    }//GEN-LAST:event_btnCadastroMouseEntered
    
    private void btnCadastroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMouseExited
        // TODO add your handling code here:
        btnCadastro.setBackground(new java.awt.Color(42,86,159));
        txtCadastro.setForeground(java.awt.Color.WHITE);
        txtCadastro.setIcon(new ImageIcon(getClass().getResource("/imagens/icons8_book_branco.png")));
    }//GEN-LAST:event_btnCadastroMouseExited

    private void btnCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroMousePressed
        // TODO add your handling code here:
        btnCadastro.setBackground(new java.awt.Color(255, 255, 255));
        txtCadastro.setForeground(java.awt.Color.BLACK);
        txtCadastro.setIcon(new ImageIcon(getClass().getResource("/imagens/icons8_book_cinza.png")));
        
        TelaCadastro cadastroLivro = new TelaCadastro();
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(cadastroLivro);
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
        
        
    }//GEN-LAST:event_btnCadastroMousePressed

    private void btnSobrePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobrePanel1MouseEntered
        // TODO add your handling code here:
        btnSobrePanel1.setBackground(new java.awt.Color(31, 121, 189));
        txtSobre1.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_btnSobrePanel1MouseEntered

    private void btnSobrePanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobrePanel1MouseExited
        // TODO add your handling code here:
        btnSobrePanel1.setBackground(new java.awt.Color(42,86,159));
        txtSobre1.setForeground(java.awt.Color.WHITE);
        txtSobre1.setIcon(new ImageIcon(getClass().getResource("/imagens/icons8_info_branco.png")));
    }//GEN-LAST:event_btnSobrePanel1MouseExited

    private void btnSobrePanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobrePanel1MousePressed
        // TODO add your handling code here:
        btnSobrePanel1.setBackground(new java.awt.Color(255, 255, 255));
        txtSobre1.setForeground(java.awt.Color.BLACK);
        txtSobre1.setIcon(new ImageIcon(getClass().getResource("/imagens/icons8_info_cinza.png")));
    }//GEN-LAST:event_btnSobrePanel1MousePressed

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:
        btnInicio.setBackground(new java.awt.Color(31, 121, 189));
        txtInicio.setForeground(java.awt.Color.WHITE);
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseExited
        // TODO add your handling code here:
        btnInicio.setBackground(new java.awt.Color(42,86,159));
        txtInicio.setForeground(java.awt.Color.WHITE);
        txtInicio.setIcon(new ImageIcon(getClass().getResource("/imagens/icons8_home_branco.png")));
    }//GEN-LAST:event_btnInicioMouseExited

    private void btnInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMousePressed
        // TODO add your handling code here:
        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtInicio.setForeground(java.awt.Color.BLACK);
        txtInicio.setIcon(new ImageIcon(getClass().getResource("/imagens/icons8_home_cinza.png")));
        
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(jConteudoInicial);
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }//GEN-LAST:event_btnInicioMousePressed

    private void jListLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLivrosMouseClicked
        // TODO add your handling code here:
       
       System.out.println("Livro teste: "+ jListLivros.getSelectedIndex());
    }//GEN-LAST:event_jListLivrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new Tela().setVisible(true);
              

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NomeApp;
    private javax.swing.JPanel btnCadastro;
    private javax.swing.JPanel btnInicio;
    private javax.swing.JPanel btnSobrePanel1;
    private javax.swing.JPanel jConteudoInicial;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JList<String> jListLivros;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtCadastro;
    private javax.swing.JLabel txtInicio;
    private javax.swing.JLabel txtSobre1;
    // End of variables declaration//GEN-END:variables
}
